### ISSUE TITLE
bars dont appear where they're set

### ISSUE THREAD

**Issue by flareonosrs** [NephMakes/NeedToKnow#8]
where i've set my bars: https://i.imgur.com/T2GGUri.png
where they appear: https://i.imgur.com/pSPlws8.png

this is after having to re-enable every group and every individual bar for the countless profiles i've made since cataclysm =)

**Comment by NephMakes** [comment]
Yeah "condense group" is now the default setting. And for some reason a former author set it up so you couldn't change the default setting without also messing with user settings. Something I gotta fix.
